services:

  api:
    build: .
    container_name: api
    restart: unless-stopped
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - red-interna

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - uptime-data:/app/data
    networks:
      - red-interna

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - red-interna

networks:
  red-interna:
    driver: bridge

volumes:
  uptime-data:
