name: DevSecOps

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: npm audit
        run: npm audit --audit-level=high

      - name: Construir imagen
        run: docker build -t api-fortaleza-nube:latest .

      - name: Escanear imagen con Trivy
        uses: aquasecurity/trivy-action@v0.24.0
        with:
          image-ref: api-fortaleza-nube:latest
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true

      
      - name: Iniciar sesión en Docker Hub
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publicar imagen
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          docker tag api-fortaleza-nube:latest ${{ secrets.DOCKERHUB_USERNAME }}/api-fortaleza-nube:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-fortaleza-nube:latest

  deploy:
    needs: security
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Desplegar por SSH en EC2
        uses: appleboy/ssh-action@v1
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: DOCKERHUB_USERNAME,DOCKERHUB_TOKEN
          script: |
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker pull "$DOCKERHUB_USERNAME/api-fortaleza-nube:latest"
            docker stop api-recuperacion || true
            docker rm api-recuperacion || true
            docker run -d --name api-recuperacion --restart unless-stopped -p 8080:8080 "$DOCKERHUB_USERNAME/api-fortaleza-nube:latest"